server:
  port: 10000

flyway:
  enabled: true
  locations: db/migration
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/dhwang?useUnicode=true&characterEncoding=GBK&useSSL=false&autoReconnect=true
    hikari:
      minIdle: 10
      idle-timeout: 10000
      maximumPoolSize: 30

